name: Deploy to Test Server

on:
  push:
    branches: [ main ]
    
env:
  REF_NAME: ${{ github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_URL: ${{ github.event.repository.url }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: 'cd /var/www/laravel-test-server && chmod +x *.sh && ./update.sh ${{ env.REF_NAME }} ${{ env.REPO_URL }} && chmod +x *.sh'
